package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.BuildType
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'PublishAll'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("PublishAll")
    name = "_PublishAll"

    type = BuildTypeSettings.Type.COMPOSITE

    vcs {
        showDependenciesChanges = true
    }

    dependencies {
        snapshot(RelativeId("CognitiveComplexity")) {
        }
        snapshot(RelativeId("CyclomaticComplexity")) {
        }
        snapshot(RelativeId("FluentAssertions")) {
        }
        snapshot(RelativeId("FluentValidation")) {
        }
        snapshot(RelativeId("HeapView")) {
        }
        snapshot(RelativeId("InternalsVisibleTo")) {
        }
        snapshot(RelativeId("PresentationAssistant")) {
        }
        snapshot(RelativeId("StyleCop")) {
        }
        snapshot(RelativeId("Xao")) {
        }
    }
}))
