package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.Project
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        expect {
            password("env.PublishToken", "", label = "PublishToken", display = ParameterDisplay.PROMPT)
        }
        update {
            password("env.PublishToken", "credentialsJSON:bbef7a45-d3f9-4476-b68e-d6d85c9a1ae0", label = "PublishToken")
        }
    }
}
