package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.Project
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        expect {
            password("env.PublishToken", "", label = "PublishToken", display = ParameterDisplay.PROMPT)
        }
        update {
            password("env.PublishToken", "credentialsJSON:f64775db-810c-4985-8e78-1735bb5f62c6", label = "PublishToken")
        }
    }
}
