package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_1.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'NUKEVcsRoot'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("NUKEVcsRoot")) {
    val expected = GitVcsRoot({
        id("NUKEVcsRoot")
        name = "https://github.com/nuke-build/resharper/#refs/heads/master"
        pollInterval = 60
        url = "https://github.com/nuke-build/resharper/"
        branch = "refs/heads/master"
        param("useAlternates", "true")
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        checkoutPolicy = GitVcsRoot.AgentCheckoutPolicy.USE_MIRRORS
        authMethod = password {
            userName = "nuke-bot"
            password = "credentialsJSON:12621440-7084-45f8-ba43-0d65201c2a53"
        }
    }

}
